jenkinsci/stapler

- core/src/main/java/org/kohsuke/stapler/compression/CompressionFilter.java
> Clarifying meaning of DISABLED

- core/src/main/java/org/kohsuke/stapler/BindInterceptor.java
- core/src/main/java/org/kohsuke/stapler/CrumbIssuer.java
- core/src/main/java/org/kohsuke/stapler/StaplerResponse.java
- core/src/main/java/org/kohsuke/stapler/WebApp.java
- core/src/main/java/org/kohsuke/stapler/bind/Bound.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
- core/src/main/java/org/kohsuke/stapler/package-info.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyClosureScript.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
- jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/AdjunctManager.java
- jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/package-info.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/AttributeConstraintsTag.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/AttributeTag.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/BindTag.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/DefaultScriptInvoker.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/HTMLWriterOutput.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/StructuredMessageArgumentTag.java
- jsp/src/main/java/org/kohsuke/stapler/tags/Include.java
- pom.xml
Trying to make this releasable to OSSRH.
Some temporary POM code pending merge & release of https://github.com/kohsuke/pom/pull/1.
@reviewbybees esp. @kohsuke and @tfennelly
> Release fixes

- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/test/java/org/kohsuke/stapler/export/ModelTest.java
https://issues.jenkins-ci.org/browse/JENKINS-26775
> [FIXED JENKINS-26775] Do not export synthetic bridge methods

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
- core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
See issue #52.
Updates the getParameter functions to take multipart/form-data form field values into account.
I marked this as a WIP coz we need to add a test or two.
> [Fix for issue 52] Added getParameter (and sister function) overrides

- core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
- core/src/test/java/org/kohsuke/stapler/AcceptHeaderTest.java
This utility code helps us handle `Accept` header with ease
@reviewbybees
> Accept header

- core/src/main/java/org/kohsuke/stapler/export/Exported.java
- core/src/main/java/org/kohsuke/stapler/export/Property.java
- core/src/test/java/org/kohsuke/stapler/export/ModelTest.java
> Adding a mechanism to skipp null property

- core/src/test/java/org/kohsuke/stapler/AcceptHeaderTest.java
Test case fix. Related to https://github.com/stapler/stapler/pull/67.
> Fixed testcase bug

- core/src/main/java/org/kohsuke/stapler/export/Property.java
- core/src/main/java/org/kohsuke/stapler/export/XMLDataWriter.java
- core/src/test/java/org/kohsuke/stapler/export/XMLDataWriterTest.java
Fixes regressions with XML serialization as reported in https://issues.jenkins-ci.org/browse/JENKINS-33546
* @ExportedBean/@Expoerted annotations not read on Collection classes
* Plural to Singular renaming fails for nested classes
> Stapler regression

- jelly/src/main/java/org/kohsuke/stapler/jelly/AttributeTag.java
@reviewbybees (esp @daniel-beck )
> Add a since tag for documentation of attributes

- Jenkinsfile
> Use steps block

- Jenkinsfile
this will settle down soon.....
@reviewbybees
> New syntax

- core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
Split from #104 
This isn't ready as someone will have to figure out how to properly deal w/ API compat.
> spelling: API parameterized

- CHANGELOG.md
Hello,
I propose to spin a new release of Stapler. In addition to already integrated fixes, I propose to merge #113 and #112. Maybe it also makes sense to consider #115 and #104, but it needs more feedback.
Created the changelog draft.
CC @reviewbybees @jglick @i386 @varyvol
> Changelog: Noting changes towards 1.251

- core/src/main/java/org/kohsuke/stapler/export/DataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/main/java/org/kohsuke/stapler/export/Property.java
Fixes incompatibilities from https://github.com/stapler/stapler/pull/61#issuecomment-190274458 & https://github.com/stapler/stapler/pull/106#discussion_r102306777, inspired by #128. Minor merge conflict expected with #127.
@reviewbybees
> Adding default implementations for some DataWriter methods

- Jenkinsfile
- pom.xml
https://github.com/stapler/stapler/pull/157 + https://github.com/jenkins-infra/repository-permissions-updater/pull/1087
> Incrementals publishing

- jrebel/pom.xml
- pom.xml
> A little bit of pom cleanup.

- core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
```
WARNING: java.lang.IllegalAccessException: Please report to the respective component:
class org.kohsuke.stapler.lang.FieldRef$1 cannot access a member of class org.kohsuke.stapler.AncestorImplTest$Foo with modifiers "public"
```
> Quieter log

- core/pom.xml
See [JENKINS-64650](https://issues.jenkins.io/browse/JENKINS-64650). Part of jenkinsci/jenkins#5174.
> JENKINS-64650: Upgrade Commons FileUpload from 1.3.1-jenkins-2 to 1.4

- core/pom.xml
- core/src/test/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessorTest.java
> With a new `annotation-indexer` comes a new index location

- .github/dependabot.yml
- core/pom.xml
- core/src/test/java/org/kohsuke/stapler/compression/CompressionFilterTest.java
- core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
- core/src/test/java/org/kohsuke/stapler/test/JettyTestCase.java
- jelly/pom.xml
- pom.xml
> Bump Jetty from 6.1.11 to 9.4.41.v20210516

- docs/getting-started.adoc
I would assume @kohsuke doesn't want email contact for stapler documentation anymore...
> Remove kk email contact

- jruby/src/test/java/org/kohsuke/stapler/jelly/jruby/haml/JRubyJellyHamlScriptTest.java
Flaked on 2 PRs recently, no point investigating due to https://github.com/stapler/stapler/pull/252#issuecomment-899534568
> Disable flakey test

- CHANGELOG.md
- core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
- jruby/src/test/java/org/kohsuke/stapler/jelly/jruby/RubyKlassNavigatorTest.java
- pom.xml
https://issues.jenkins.io/browse/INFRA-2908
> INFRA-2908 Update URLs for new home in jenkinsci

- core/src/main/java/org/kohsuke/stapler/framework/AbstractWebAppMain.java
Making copypasta in Stapler conform to jenkinsci/jenkins#6111.
> Remove JNDI support

- core/pom.xml
- groovy/pom.xml
- jelly/pom.xml
- jrebel/pom.xml
- jsp/pom.xml
- pom.xml
Sorts dependencies by group ID and artifact ID.
> Sort dependencies

- .github/dependabot.yml
- core/pom.xml
- groovy/pom.xml
Matches the corresponding bump in core.
> Bump Groovy from 2.4.12 to 2.4.21

- .github/dependabot.yml
> Block incompatible version of JSP

- jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java
This code contained a TODO for Java 9+. We're on Java 11 now, so the TODO can be completed.
> Simplify code for Java 11

- core/src/test/java/org/kohsuke/stapler/AncestorImplTest.java
- core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
- core/src/test/java/org/kohsuke/stapler/Stapler2Test.java
- core/src/test/java/org/kohsuke/stapler/bind/BoundObjectTableTest.java
- core/src/test/java/org/kohsuke/stapler/bind/JavaScriptProxyTest.java
- core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
- core/src/test/java/org/kohsuke/stapler/json/JsonBodyTest.java
- core/src/test/java/org/kohsuke/stapler/json/SubmittedFormTest.java
- core/src/test/java/org/kohsuke/stapler/test/JettyTestCase.java
- jelly/src/test/java/org/kohsuke/stapler/jelly/AttributeExpressionTest.java
- jelly/src/test/java/org/kohsuke/stapler/jelly/BindTagTest.java
- jelly/src/test/java/org/kohsuke/stapler/jelly/BodyExpressionTest.java
- jelly/src/test/java/org/kohsuke/stapler/jelly/TagLibNamespaceExportTest.java
- jelly/src/test/java/org/kohsuke/stapler/jelly/issue76/Issue76Test.java
- pom.xml
Part of https://github.com/jenkinsci/jenkins-test-harness/issues/568
Tests passed locally
> Update htmlunit to 3.x

- jelly/pom.xml
https://github.com/jenkinsci/jellydoc-maven-plugin/releases/tag/129.vf7c31dffdf17
> Adapt jellydoc-maven-plugin rebrand

- core/src/main/java/org/kohsuke/stapler/TokenList.java
- core/src/main/java/org/kohsuke/stapler/export/ExportConfig.java
- pom.xml
Prep for
* https://github.com/jenkinsci/pom/pull/510
Part of the checklist in:
* https://github.com/jenkinsci/jenkins/pull/8803
Confirmed that automated tests pass and spotbugs is silent.
> Use spotbugs 4.8.2 with more exclusions

- core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
- core/src/main/java/org/kohsuke/stapler/Function.java
- core/src/main/java/org/kohsuke/stapler/KlassDescriptor.java
- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/TruncatedInputStream.java
- core/src/main/java/org/kohsuke/stapler/bind/BoundObjectTable.java
- core/src/main/java/org/kohsuke/stapler/export/FieldProperty.java
- core/src/main/java/org/kohsuke/stapler/export/PythonDataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/RubyDataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
- core/src/main/java/org/kohsuke/stapler/interceptor/JsonOutputFilter.java
- core/src/main/java/org/kohsuke/stapler/jsr269/AbstractProcessorImpl.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovierJellyScript.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/AttributeNameRewritingTagScript.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/CustomJellyContext.java
- jsp/src/main/java/org/kohsuke/stapler/jsp/RequestDispatcherWrapper.java
- jsp/src/main/java/org/kohsuke/stapler/tags/Include.java
Fixes [this Checkstyle check](https://checkstyle.sourceforge.io/checks/modifier/redundantmodifier.html) by removing redundant modifiers.
> Remove redundant modifiers

- core/src/main/java/org/kohsuke/stapler/AnnotationHandler.java
- core/src/main/java/org/kohsuke/stapler/AttributeKey.java
- core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
- core/src/main/java/org/kohsuke/stapler/ClassLoaderValue.java
- core/src/main/java/org/kohsuke/stapler/Function.java
- core/src/main/java/org/kohsuke/stapler/MetaClassLoader.java
- core/src/main/java/org/kohsuke/stapler/SingleLinkedList.java
- core/src/main/java/org/kohsuke/stapler/TearOffSupport.java
- core/src/main/java/org/kohsuke/stapler/export/Iterators.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/main/java/org/kohsuke/stapler/export/Range.java
- core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
- core/src/main/java/org/kohsuke/stapler/jsr269/ConstructorProcessor.java
- core/src/main/java/org/kohsuke/stapler/lang/KlassNavigator.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
- jelly/src/test/java/org/kohsuke/stapler/jelly/issue76/ProtectedClass.java
> Use diamond operator where possible

- core/src/main/java/org/kohsuke/stapler/AttributeKey.java
- core/src/main/java/org/kohsuke/stapler/BytecodeReadingParanamer.java
- core/src/main/java/org/kohsuke/stapler/CachingScriptLoader.java
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
- core/src/main/java/org/kohsuke/stapler/framework/io/WriterOutputStream.java
- core/src/test/java/org/kohsuke/stapler/framework/io/LargeTextTest.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovierJellyScript.java
- groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
Fixing various one-off IntelliJ warnings. Tested with `mvn clean verify`.
> Miscellaneous code cleanup

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
Elements that convert to `null` are considered invalid/unwanted, so adding those `null` values is invalid/unwanted as well.
This fixes the the underlying issue from https://issues.jenkins.io/browse/JENKINS-75468.
The initial attempt to fix that issue (https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/778) led to discussions indicating it was an issue with stapler and not individual plugins.
Rather than doing the filtering at every point where elements were added to a collection, I opted to effectively create a collection that did not allow `null` elements.  A simpler solution would be to modify `Lister` itself, but it (technically) lives outside the Jenkins umbrella.
There is a new unit test which approximates the original issue.  This new test passes, all existing tests …
> [JENKINS-75468] Omit null elements from collections during databinding

- core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
- core/src/main/java/org/kohsuke/stapler/bind/BoundObjectTable.java
I merged #691 a little too eagerly, as we were still using Commons Lang in a handful of places.
> Remove usages of Commons Lang
