jenkinsci/stapler

- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/TokenList.java
See [JENKINS-27256](https://issues.jenkins-ci.org/browse/JENKINS-27256).
Added dispatcher for `getX(long)` style model methods. Already tested manually but will add a functional test in Jenkins core test harness (yeah, should have done that first etc etc).
@reviewbybees
> [FIXED JENKINS-27256] Dispatcher for getX(long) model object methods

- core/src/main/java/org/kohsuke/stapler/export/Flavor.java
add the JSONP flavour for avoid:
Refused to execute script from 'TARGET URL' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled
> Add the JSONP Flavor

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
[JENKINS-27918](https://issues.jenkins-ci.org/browse/JENKINS-27918)
It is confusing and annoying to repeatedly print a warning to the log when Jenkins core still produces `stapler-class` (despite https://github.com/jenkinsci/jenkins/pull/1443) and there is nothing a user or plugin developer can do about it. Was suggested that this be downgraded in https://github.com/stapler/stapler/commit/82b0a45924b083796d04c94661bbef7b80e2d2bf which introduced this warning.
Cf. #39 and https://github.com/jenkinsci/jenkins/pull/1563.
@reviewbybees
> [JENKINS-27918] Downgrade stapler-class warning to FINE

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessor.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/RequirePOSTAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/Utils.java
- core/src/test/java/org/kohsuke/stapler/jsr269/WebMethodAnnotationProcessorTest.java
- jelly/pom.xml
- jruby/pom.xml
- pom.xml
- Update dependencies where needed
- annotation-indexer ([to be released](https://github.com/jenkinsci/lib-annotation-indexer/pull/2))
- jruby-complete
- animal-sniffer-maven-plugin
- metainf-services
- Replace explicit `tools.jar` dependency with [`maven-jdk-tools-wrapper`](https://github.com/olivergondza/maven-jdk-tools-wrapper)
- Fix tests and `java.nio.file.NoSuchFileException` usage
> Make stapler JDK 9 ready

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
In Jenkins this shows up at Slave.nodeProperties whose setter accepts
List but getter returns more specific DescribableList.
@reviewbybees
> BeanInfo doesn't work when there's assymetry in getter vs setter

- core/src/main/java/org/kohsuke/stapler/StaplerResponseWrapper.java
... for wrapping functionality downstream if needed (e.g. capturing output by overriding getWriter()).
@reviewbybees esp. @jglick
> Add StaplerResponseWrapper

- core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
- core/src/test/java/org/kohsuke/stapler/AcceptHeaderTest.java
AcceptHeader.select() gives wrong result if first mime  type is of lower q value than the second parameter mime type.
Given this accept header:
AcceptHeader ah = new AcceptHeader("    text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
ah.select("text/plain", "text/html");  //gives text/plain, where as it should give text/html as text/html's q is 1 where as text/plain q is 0.8 (*/*)
> AcceptHeader doesn't honor relative weight in certain cases

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
- core/src/test/java/org/kohsuke/stapler/framework/io/LargeTextTest.java
[JENKINS-37664](https://issues.jenkins-ci.org/browse/JENKINS-37664)
@reviewbybees
> [JENKINS-37664] Immediately throw an EOF in a boundary error condition

- core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
- core/src/main/java/org/kohsuke/stapler/lang/Klass.java
- core/src/main/java/org/kohsuke/stapler/lang/util/FieldRefFilter.java
- core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
- jruby/pom.xml
Fixes regression where a declared field on a superclass not detected by stapler resulting in 404 when accessed from URL, as reported on https://github.com/jenkinsci/jenkins/pull/2415.
> Look for declared fields on superclass

- core/src/main/java/org/kohsuke/stapler/Stapler.java
To get served with compression, the MIME type of a static resource must either be `TEXT/*` or the file extension must be contained in `TEXT_FILES`. See https://github.com/stapler/stapler/blob/stapler-parent-1.244/core/src/main/java/org/kohsuke/stapler/Stapler.java#L532.
The MIME Type for `.json` files is `application/json`. JSON resources are never compressed since the MIME type is not `text/*` and `json` is not in `TEXT_FILES`.
> allow JSON responses to be compressed when serving with serveStaticResource

- core/src/main/java/org/kohsuke/stapler/lang/Klass.java
- core/src/test/java/org/kohsuke/stapler/lang/KlassTest.java
- jruby/pom.xml
- jruby/src/test/java/org/kohsuke/stapler/jelly/jruby/RubyKlassNavigatorTest.java
Stapler 1.266 was formally compatible if we take a set of modules, but we didn't take into account that components like `stapler-jruby` are actually standalone libs being bundled in plugins like Ruby Runtime.
Verifies there is no regression in the Jenkins core itself.
Error suppression is a weird approach, but I cannot offer anything better in the current state. A long-term fix would be to rework Stapler multi-module structure and to somehow ensure that entire stapler code gets delivered via something like core module
https://issues.jenkins-ci.org/browse/JENKINS-39414
@reviewbybees
> [JENKINS-39414] - Workaround Ruby Runtime Plugin and Jenkins 2.28 compatibility issues

- core/src/main/java/org/kohsuke/stapler/lang/Klass.java
- core/src/main/java/org/kohsuke/stapler/lang/KlassNavigator.java
- core/src/main/java/org/kohsuke/stapler/lang/MethodRef.java
- core/src/main/java/org/kohsuke/stapler/lang/util/MethodRefFilter.java
- core/src/test/java/org/kohsuke/stapler/lang/KlassTest.java
- jruby/src/main/java/org/kohsuke/stapler/jelly/jruby/RubyMethodRef.java
- jruby/src/test/java/org/kohsuke/stapler/jelly/jruby/RubyKlassNavigatorTest.java
1.247 didn't fix the issue completely, because there was another incompatible method (`getFunctions()`), which I have missed somehow.
This change intends to solve the binary compat issue:
I've verified that Ruby Runtime plugin starts correctly and shows UIs without errors in System logs after the fix.
https://issues.jenkins-ci.org/browse/JENKINS-39414
@reviewbybees
> [JENKINS-39414] - Stapler 1.246 Binary Incompatibility. Part 2

- core/src/main/java/org/kohsuke/stapler/StaplerRequest.java
- core/src/main/java/org/kohsuke/stapler/json/SubmittedForm.java
- core/src/test/java/org/kohsuke/stapler/json/SubmittedFormTest.java
- core/src/test/resources/org/kohsuke/stapler/json/SubmittedFormTest/form.html
This makes it easier to write a `doConfigSubmit` method that's more amenable for overriding
> Define an annotation to inject `req.getSubmittedForm()`

- Jenkinsfile
- core/src/main/java/org/kohsuke/stapler/Function.java
- core/src/main/java/org/kohsuke/stapler/MethodHandleCache.java
- core/src/main/java/org/kohsuke/stapler/export/MethodProperty.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- pom.xml
Use invoke dynamic (`MethodHandles`)  instead of Method.invoke for @Exported. 
`MethodHandles` seem to be what all the cool serialisers like protobuf use for performance reasons. This means that Stapler has to require JDK 7 minimum.
Initial testing seemed to show I could shave 20% off of the time to serve some Blue Ocean rest calls.
> [Performance] Use invoke dynamic instead of Method.invoke for @Exported

- core/src/main/java/org/kohsuke/stapler/export/Property.java
- core/src/test/java/org/kohsuke/stapler/export/JSONDataWriterTest.java
- pom.xml
We were already catching `NotExportableException`, a common problem, but not other miscellaneous exceptions.
[JENKINS-40083](https://issues.jenkins-ci.org/browse/JENKINS-40083) should not have caused the whole API call to fail. The test output before the fix:
```
java.io.IOException: Failed to write generic
at org.kohsuke.stapler.export.Property.safeGetValue(Property.java:151)
at org.kohsuke.stapler.export.Property.writeTo(Property.java:126)
at org.kohsuke.stapler.export.Model.writeNestedObjectTo(Model.java:227)
at org.kohsuke.stapler.export.Property.writeValue(Property.java:279)
at org.kohsuke.stapler.export.Property.writeValue(Property.java:222)
at org.kohsuke.stapler.export.Property.writeValue(Property.java:168)
at org.kohsuke.stapler.export.Property.writeTo(Property.java:139)
at …
```
> [JENKINS-40088] Be more robust when exporting collections

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/main/java/org/kohsuke/stapler/WrongTypeException.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
When the same parameter name is used several times in a form, it is
submitted as an array to Stapler, which in turn expects to find a list
type in the data model.  If this is not the case, report a meaningful
error message instead of a cryptic NPE.
> Detect wrong array type in RequestImpl.convertJSON()

- core/src/main/java/org/kohsuke/stapler/DirectoryishDispatcher.java
- core/src/main/java/org/kohsuke/stapler/HttpDeletable.java
- core/src/main/java/org/kohsuke/stapler/IndexViewDispatcher.java
- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
Adjustment of pull request #97 
The goal of #97 was to improve performance of request routing to objects that do not have index views but do have the `doIndex` method. This is achieved by swapping the priority between those two routes, which was done in 8156216. This is strictly speaking an incompatible change, but in practice acceptable and preferrable because:
1. no valid code could have existed out there that has both index view and the `doIndex` method because the latter would have never been invoked
2. the change makes the relative order of view and web method the same between index (index.jelly vs doIndex) and regular routes (xyz.jelly vs doXyz.)
To make this possible, this PR also converts index view routing and a few other routes that were previously hard-coded in …
> Prefer doIndex over index views

- core/src/main/java/org/kohsuke/stapler/Facet.java
- core/src/main/java/org/kohsuke/stapler/IndexHtmlDispatcher.java
- core/src/main/java/org/kohsuke/stapler/IndexViewDispatcher.java
- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/StaticViewFacet.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyFacet.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyFacet.java
- jrebel/src/main/java/org/kohsuke/stapler/JRebelFacet.java
- jruby/src/main/java/org/kohsuke/stapler/jelly/jruby/JRubyFacet.java
This PR builds on top of PR #101 to improve the request routing performance by resolving the available index view routes upfront.
That is, instead of looking for a presence of `index.jelly` (and the likes) at the request processing time, this change makes that check happen during `MetaClass` construction time.
> Fast index view search

- CHANGELOG.md
- core/src/main/java/org/kohsuke/stapler/Function.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
Corrects a regression in #96 caught by tests in https://github.com/jenkinsci/jenkins/pull/2722. [This code](https://github.com/jenkinsci/cvs-plugin/blob/9390d5ae0b07c29c87adc87ae10be302507a5347/src/main/java/hudson/scm/CvsRepository.java#L221) in the CVS plugin is a mistake, but was apparently tolerated before.
@reviewbybees esp. @i386
> Fix use of MethodHandle on web methods which were accidentally static

- core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
- core/src/main/java/org/kohsuke/stapler/StaplerResponse.java
- core/src/main/java/org/kohsuke/stapler/StaplerResponseWrapper.java
- core/src/main/java/org/kohsuke/stapler/export/DataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/ExportConfig.java
- core/src/main/java/org/kohsuke/stapler/export/ExportInterceptor.java
- core/src/main/java/org/kohsuke/stapler/export/FieldProperty.java
- core/src/main/java/org/kohsuke/stapler/export/Flavor.java
- core/src/main/java/org/kohsuke/stapler/export/JSONDataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/MethodProperty.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/main/java/org/kohsuke/stapler/export/Property.java
- core/src/main/java/org/kohsuke/stapler/export/XMLDataWriter.java
- core/src/test/java/org/kohsuke/stapler/export/ClassAttributeBehaviourTest.java
- core/src/test/java/org/kohsuke/stapler/export/JSONDataWriterTest.java
- core/src/test/java/org/kohsuke/stapler/export/ModelTest.java
- core/src/test/java/org/kohsuke/stapler/export/NamedPathPrunerTest.java
- core/src/test/java/org/kohsuke/stapler/export/XMLDataWriterTest.java
This PR bring customization feature where plugins like blueocean can configure stapler and participate during property serialization and decide whether to fail or skip serialization. 
Implementation is pretty much based on @i386 [proposal](https://docs.google.com/document/d/1AalzfYZ0HDfwtFMUNaw_okWMLaaQ0S5Q1o6L4taevL4/edit#heading=h.vr11cprbtd0) sent at dev list some time back. Further this custom serialization approach is followup of [PR 89](https://github.com/stapler/stapler/pull/89#issuecomment-272307140) to fix it in generic way.
> JENKINS-40088# Configurable stapler serialization behavior

- core/src/main/java/org/kohsuke/stapler/IndexHtmlDispatcher.java
- core/src/test/java/org/kohsuke/stapler/IndexHtmlDispatcherTest.java
[Issue #109](https://github.com/stapler/stapler/issues/109)
Interfaces do not have a superclass and thus a NPE exception was happening.
@reviewbybees @jglick @oleg-nenashev
> Quietly ignore interfaces in IndexHtmlDispatcher, avoiding NPE.

- core/src/main/java/org/kohsuke/stapler/export/FilteringTreePruner.java
Discovered that in certain conditions `child` can be null and cause an NPE https://github.com/jenkinsci/blueocean-plugin/pull/996
> JENKINS-40979  NPE where child can be null

- core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
- core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
Has sometimes been observed that a web method with multiple overloads will randomly run one or the other (according to JVM implementation details), which is confusing and can lead to bugs, especially if all but one overload was intentionally deprecated. This patch simply picks one nondeprecated overload consistently so there are no surprises (as in https://github.com/junit-team/junit4/pull/293 for example).
@reviewbybees
> Make ClassDescriptor deterministic

- core/src/main/java/org/kohsuke/stapler/CrumbIssuer.java
- core/src/main/java/org/kohsuke/stapler/HttpResponses.java
- core/src/main/java/org/kohsuke/stapler/bind/BoundObjectTable.java
- core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
More compatible alternative to #92. Fixes #91.
@reviewbybees
> Replace HttpResponses methods adding platform-specific newlines

- core/src/main/java/org/kohsuke/stapler/config/ConfigurationLoader.java
- core/src/main/java/org/kohsuke/stapler/framework/io/AtomicFileWriter.java
- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
See [JDK-8080225](https://bugs.openjdk.java.net/browse/JDK-8080225) and [JENKINS-45903](https://issues.jenkins-ci.org/browse/JENKINS-45903)
@reviewbybees
> [JENKINS-45903] Switch to Files.new(Input|Output)Stream(...) to avoid file handle leak

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/export/Range.java
Was noted in https://github.com/jenkinsci/plugin-pom/pull/67.
@reviewbybees
> [JENKINS-41631] Lower Guava dep to 11, which is what Jenkins still uses

- core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
- pom.xml
Relevant since Jenkins core is now on `-source 8`.
@reviewbybees
> Verifying that web methods may be defined as default interface methods

- core/src/main/java/org/kohsuke/stapler/StaplerResponse.java
https://github.com/stapler/stapler/pull/106 added a new method in StaplerResponse, causing backward compatibility issue in a closed source plugin.
As Stapler bumped to Java 8, this change leverages default method to make it more compatible.
@reviewbybees esp. @jglick @vivek @jtnord
> Use default method for better backward compatibility

- core/src/main/java/org/kohsuke/stapler/export/ModelBuilder.java
- core/src/main/java/org/kohsuke/stapler/export/Property.java
Removes additional millis per call on large exports by avoiding throwing `NotExportableException` and instead using annotation check to check exportability e.g. `type.getAnnotation(ExportedBean.class)`
See https://github.com/jenkinsci/blueocean-plugin/pull/1323
@reviewbybees #NightTimeCode
> [Performance] Export Model constructor throws exceptions on very hot paths

- core/maven-example/pom.xml
- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
- core/src/main/java/org/kohsuke/stapler/StaplerResponseWrapper.java
- core/src/main/java/org/kohsuke/stapler/compression/CompressionServletResponse.java
- core/src/main/java/org/kohsuke/stapler/compression/FilterServletOutputStream.java
- core/src/test/java/org/kohsuke/stapler/MockRequest.java
- core/src/test/java/org/kohsuke/stapler/MockServletContext.java
- core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
- core/src/test/java/org/kohsuke/stapler/ResponseImplTest.java
- groovy/pom.xml
- jelly/pom.xml
- jrebel/pom.xml
- jruby/pom.xml
- jsp/pom.xml
Update stapler to use Servlet API 3.1.0 (and other servlet APIs coming from Java EE 7)
Fixes #114 
Code could be cleaned up further with the inclusion of #130 
* updated API to compiled against Java Servlet API 3.1.0, JSP API 2.3.0 and JSTL API 1.2.1
* This required a API signature change of `org.kohsuke.stapler.compression.FilterServletOutputStream`.
* It is recommended that users of this class do not upgrade but replace the implementation as this call may be removed in a future version.
@reviewbybees
> [stapler#114] Update to Servlet API 3.1.0

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
- groovy/pom.xml
- jelly/pom.xml
- pom.xml
Subsumes #133 and fixes the bug turned up there.
@reviewbybees esp. @oleg-nenashev
> Dependency updates

- core/pom.xml
- groovy/pom.xml
- jelly/pom.xml
- pom.xml
All versions are compatible with the Jenkins core.
@reviewbybees @jglick
> Resolve Upper Bound issues, update Groovy

- core/src/main/java/org/kohsuke/stapler/interceptor/RequirePOST.java
I'm pretty sure `requestURL` is mostly redundant, but cannot really hurt either to make it easily accessible.
Downstream use: https://github.com/jenkinsci/jenkins/pull/3187
> [JENKINS-34254] Allow customizing RequirePOST error pages

- core/src/main/java/org/kohsuke/stapler/export/ExportInterceptor.java
Silently dropping properties has been causing issues in front-end code; this will add logging so we'll have something to look for when this happens in the future.
See: https://issues.jenkins-ci.org/browse/JENKINS-48198
> Log when a property is left out of serialised result due to exception

- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
It seems Stapler documents returning `null` from `getTarget()` to backtrack (or abort dispatching), but in reality, it doesn't work that way: It's the same as returning `this`.
I noticed this bug when trying to conditionally have an object not handle a request at all (when the user has no permission to `Item/Read` it) and fall back to Stapler failing to route.
Upstream of https://github.com/jenkinsci/jenkins/pull/3690
> Actually allow returning null from StaplerProxy

- core/src/main/java/org/kohsuke/stapler/Dispatcher.java
- core/src/main/java/org/kohsuke/stapler/EvaluationTrace.java
- core/src/main/java/org/kohsuke/stapler/IndexDispatcher.java
- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/StaticViewFacet.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyFacet.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyClassTearOff.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyFacet.java
Upstream from https://github.com/jenkinsci/jenkins/pull/3688
> Trace Stapler request processing

- core/src/test/java/org/kohsuke/stapler/DispatcherTest.java
- pom.xml
Clarifies behavior of aca8c023adbc051c80a5e1d785ca76411ff9ed32 based on [this check](https://github.com/stapler/stapler/blob/cebe82d8aee82f93797f315a230fcc74ff950f64/core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java#L168).
> Added DispatcherTest.testProtectedMethodDispatch

- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
- core/src/test/java/org/kohsuke/stapler/framework/io/LargeTextTest.java
At the end of LargeText.writeLogTo() the size size is returned back as
a long, but the calculation is done with int math, not long.  So we get
a problem for large files.
This fix enables files longer than Integer.MAX_VALUE to be handled.
Unfortunately the only way to test this is by writing out a file that is
larger than Integer.MAX_VALUE.  This test takes 24 seconds to run on my
MacBookPro 15" (2015), which has a very fast SSD.  To test in any other
way would mean much larger changes to LargeFile, just for test purposes.
> Enable large log files to be downloaded. Fix for #141

- .mvn/extensions.xml
- .mvn/maven.config
- core/pom.xml
- groovy/pom.xml
- jelly/pom.xml
- jrebel/pom.xml
- jruby/pom.xml
- jsp/pom.xml
- pom.xml
I'd like to incrementalize stapler. This will be handy in general and will make it easier to do some other changes we want.
Since stapler isn't a plugin, I couldn't follow the easy mechanism. Instead I followed the step-by-step, manual instructions. The changes match what I've seen the automated, easy version do, plus the addition of the profiles needed because the parent is different.
While I've used this to effectively generate incrementals locally I don't know that it is sufficient to automatically generate them in Jenkins CI environment. Specifically, updates my be required for the stapler settings in repository-permissions-updater.
Do we want a Jira ticket associated with this change?
> Add incrementals

- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/test/java/org/kohsuke/stapler/MetaClassTest.java
There seems to be no legitimate use case for allowing `#getClass()` to be called, and not allowing it will make the following statement true:
> It's a fundamental property in Stapler's use of naming convention for its routing, and carefully written applications can just not expose public fields or methods matching the conventional `getWhatever` name on objects they make reachable through routing unless they're intended to be routed, and thereby sidestep the problem.
https://github.com/stapler/stapler/issues/153#issuecomment-445966538 has a more limited variant of that, and there's no reason it should not be true.
Untested.
@Wadeck
> Always reject the #getClass() method

- core/src/main/java/org/kohsuke/stapler/LocaleDrivenResourceProvider.java
Was irritated to see an extra message in the Jenkins startup log. https://github.com/stapler/stapler/pull/156#discussion_r273059383
> Make LocaleDrivenResourceProvider quieter

- core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
but then 2 wrongs made a right.
Fixes the logic so that is does what you would expect from the method signature.
This is slightly less optimal than renaming the method but I find having negatives in method names makes code less easy to follow.
> acceptsGzip logic was inverted

- jelly/pom.xml
- jelly/src/main/java/org/kohsuke/stapler/jelly/ContentTypeTag.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/DefaultScriptInvoker.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/HTMLWriterOutput.java
See [JENKINS-53322](https://issues.jenkins-ci.org/browse/JENKINS-53322).
I've been working on eliminating the need for the Jenkins-specific fork of dom4j and adopting the latest, standard release, 2.1.1. There are two aspects 1) dealing with the changes in the fork, which are minor and apparently not consequential, and 2) upgrading a couple of places to match changes in the dom4j API since long ago.
I've run a lot of builds and tests on various components to check these changes. I have found a few places that require changes, A) here in Stapler, B), a test in Jenkins core for API changes, C) licensing packaging change in Jenkins, D) and a couple of minor changes in ec2-plugin for API changes. My PR for ec2-plugin jenkinsci/ec2-plugin#372 works on both the old and new API and has already …
> [JENKINS-53322] Use standard dom4j distribution.

- core/src/main/java/org/kohsuke/stapler/HttpResponses.java
Add a mechanism to control whether `HttpResponses.error()` shows the error details, particularly the stack trace. By default it doesn't show the stack trace, but the interface can be enabled to show it.
> Add a mechanism to suppress stack trace.

- core/src/main/java/org/kohsuke/stapler/jsr269/ConstructorProcessor.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
Fixes #179 via https://github.com/stapler/stapler/pull/180#issuecomment-592713908. @MRamonLeon and the usual suspects @jvz @jeffret-b et al.
> Improve message regarding duplicated annotated constructors (II)

- core/pom.xml
- core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
Supersedes #175. See also https://github.com/apache/commons-fileupload/commit/96f8f56556a8592bfed25c82acedeffc4872ac1f + https://github.com/apache/commons-fileupload/commit/b50acb3c1e506a2d7317ee17a7c48b289814de63 + https://github.com/jenkinsci/jenkins/blob/277d725572aa9545062db1b5b9781b33bf9bf7e6/bom/pom.xml#L259
@jeffret-b @jvz et al.
> Update commons-fileupload to match that used in Jenkins

- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
Hopefully this will take care of cases such as [JENKINS-62985](https://issues.jenkins-ci.org/browse/JENKINS-62985)
This was manually tested with the incremental produced from this PR locally and it fixes the issue.
> [JENKINS-62985] Prevent resource leakages in sessions

- core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
Some simple testing seems to show this is ok
> Don't use setAccessible, fixes illegal reflective access warnings

- core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
```
Dec 15, 2020 2:12:32 PM org.kohsuke.stapler.lang.FieldRef$1 get
WARNING: java.lang.IllegalAccessException: Processing this request relies on deprecated behavior that will be disallowed in future releases of Java. See https://jenkins.io/redirect/stapler-reflective-access/ for more information. Details: class org.kohsuke.stapler.lang.FieldRef$1 cannot access a member of class org.kohsuke.stapler.AncestorImplTest$Foo with modifiers "public"
```
https://github.com/jenkins-infra/jenkins.io/pull/4026
> Better log message

- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
When using a groovy view and passing a groovy expression as
`"${e1}${e2}"` to a taglib, the resulting value is not coerced to a
String, which can lead to incorrect results when calling functions from
within jelly.
For example, when declaring a widget in Jenkins, using the following `index.groovy` as view
```
def l = namespace(lib.LayoutTagLib);
l.pane(width:2, title:"Title", id:"${my.urlName}", collapsedText:"CollapsedText") {
text('Foo')
}
```
In the resulting map that is passed to `JellyBuilder`, `id` has type `GStringImpl`, unlike `title` or `collapsedText` which get coerced to `String`.
Then in https://github.com/jenkinsci/jenkins/blob/62546443947fafecc94a5e3b47bb9129bed8e148/core/src/main/resources/lib/layout/pane.jelly#L51, the function call doesn't happen because `attr.id` is a …
> Convert `GString` to `String` when bridging to jelly.

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
- core/src/main/java/org/kohsuke/stapler/lang/MethodRef.java
- core/src/main/java/org/kohsuke/stapler/util/IllegalReflectiveAccessLogHandler.java
MethodRef could be triggered on the Jenkins core configuration page before
After moving the setAccessible to not the default I haven't been able to trigger it
Databoundsetter i haven't been able to trigger an error with but figured it made sense to make that change
> Handle more cases of illegal reflective access

- core/src/main/java/org/kohsuke/stapler/export/FilteringTreePruner.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
Despite the fact that `com.google.common.base.Predicate` is used in public APIs, it is safe to migrate this to `java.util.function.Predicate`.
The only references in sources are to a copy of Stapler in the `io.jenkins.blueocean.commons.stapler.export` package namespace, apparently added in jenkinsci/blueocean-plugin#711. These references are to a different package and we are not affecting them in this change.
- [`FilteringTreePruner`](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+%22FilteringTreePruner%22)
- [`HAS_PROPERTY_NAME`](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+%22HAS_PROPERTY_NAME%22)
- [`HAS_PROPERTY_NAME_IN_ANCESTRY`](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+%22HAS_PROPERTY_NAME_IN_ANCESTRY% …
> Migrate from com.google.common.base.Predicate to java.util.function.Predicate

- core/src/main/java/org/kohsuke/stapler/config/ConfigurationLoader.java
Usage of the Guava `com.google.common.base.Function` type was limited to a private field and a private constructor, so we can safely migrate to `java.util.function.Function` without breaking compatibility.
> Migrate from com.google.common.base.Function to java.util.function.Function

- core/pom.xml
- jelly/src/main/java/org/kohsuke/stapler/jelly/AttributeNameRewritingTagScript.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/CustomJellyContext.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/IncludeTag.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/StaplerTagLibrary.java
This pull request attempts to update to `commons-beanutils:1.9.4` without disabling the additional protection it offers around the `class` attribute.
It seems in my (fairly limited so far) testing that the problem is `st:include`'s `class` attribute. So this pull request renames the attribute to `clazz` (and keeps the existing setter for compatibility).
This PR additionally proposes a workaround that applies when Jelly files are being parsed and the resulting tags are created: For the `st:include` tag, when the `class` attribute would be set, instead set `clazz`. This attempts to take care of all existing code that sets the `class` attribute for this tag.
I am unsure how best to go about ensuring this doesn't cause a lot of problems. While this fix looks fairly safe, it may also be …
> Update to commons-beanutils:1.9.4 without disabling the protection

- core/src/main/java/org/kohsuke/stapler/framework/AbstractWebAppMain.java
According to [this guide](https://github.com/krka/java8-future-guide), `SettableFuture.create()` can be replaced with Java 8's `new CompletableFuture()`. I did so in Stapler, then tried to test the change. Unfortunately I could not find any usages of `org.kohsuke.stapler.framework.AbstractWebAppMain` in order to test the change. Jenkins core itself has its own implementation of `ServletContextListener`, `hudson.WebAppMain` (which does not use `org.kohsuke.stapler.framework.AbstractWebAppMain`). On the plus side, if `org.kohsuke.stapler.framework.AbstractWebAppMain` is unused then at least I know I will not be breaking anything by changing it.
The only references to [`AbstractWebAppMain`](https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+%22AbstractWebAppMain%22) in …
> Migrate from com.google.common.util.concurrent.SettableFuture to Java 8 java.util.concurrent.CompletableFuture

- core/src/main/java/org/kohsuke/stapler/export/JSONDataWriter.java
Improve performance when encoding escape sequences.
String.format has to compile the pattern for each character which consumes a lot of CPU time when requesting larger json data.
Use bit shift and lookup to simplify conversion.
Doing a small comparison on my notebook reveals:
* oldStyle 522ms
```
public StringBuilder oldStyle() {
StringBuilder b = new StringBuilder();
for(int i=0;i<0xffff;i++) {
b.append("\\u" + String.format("%04x", i));
}
return b;
}
```
* newStyle 13ms
```
private static final char[] HEX = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};
public StringBuilder newStyle() {
StringBuilder b = new StringBuilder();
for(int i=0;i<0xffff;i++) {
b.append("\\u");
b.append(HEX[(i >> 12) & 0xf]);
b.append(HEX[(i >> 8) & 0xf]);
b.append(HEX[(i >> 4) …
```
> [JENKINS-65442] json api improve performance when encoding unicode characters

- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyClassLoaderTearOff.java
A subset of #213 that is hopefully non-controversial and safe to land in the short term because it does not involve Caffeine or shading.
> Migrate from Guava's cache to `ConcurrentHashMap` in `JellyClassLoaderTearOff`

- core/src/main/java/org/kohsuke/stapler/export/Iterators.java
- core/src/main/java/org/kohsuke/stapler/export/Range.java
A subset of #213 that is hopefully non-controversial and safe to land in the short term because it does not involve Caffeine or shading.
> Inline Guava's `Iterators#limit`

- core/pom.xml
Jenkins core ships `commons-discovery` 0.4 in the WAR file, via Stapler. This version was released sometime in 2006. The latest version of `commons-discovery` is 0.5, released sometime around 2011 (see the [release notes](https://archive.apache.org/dist/commons/discovery/RELEASE-NOTES.txt)). `usage-in-plugins` shows that nothing uses this library in the Jenkins ecosystem beyond Stapler and Jenkins core itself in `CLICommand`. I'll run the main Jenkins test suite against the incremental produced from this PR to make sure it still passes.
> Bump `commons-discovery` from 0.4 to 0.5

- core/pom.xml
- groovy/pom.xml
- jruby/pom.xml
Bumps various dependencies to the latest versions. Jenkins core was already using the new versions from this PR at runtime, and Jenkins core is the only real consumer of Stapler, so this PR is more or less a no-op.
> Bump various dependencies to latest versions

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
In commit b3f1bcb41 Kohsuke adopted a repackaged ASM to avoid conflicts. While valid at the time, I don't think it makes much sense to continue to do this. First, it is a maintenance burden on the Jenkins project to release repackaged versions of ASM every time upstream releases a new version. Second, recent versions of Jenkins core already include the upstream version of ASM transitively via JNR:
```
+- com.github.jnr:jnr-posix:jar:3.1.5:compile
|  +- com.github.jnr:jnr-ffi:jar:2.2.2:compile
|  |  +- com.github.jnr:jffi:jar:1.3.1:compile
|  |  +- com.github.jnr:jffi:jar:native:1.3.1:runtime
|  |  +- org.ow2.asm:asm:jar:9.1:compile
|  |  +- org.ow2.asm:asm-commons:jar:9.1:compile
|  |  +- org.ow2.asm:asm-analysis:jar:9.1:compile
|  |  +- org.ow2.asm:asm-tree:jar:9.1:compile
|  |  +- …
```
> Stop using repackaged ASM; upgrade ASM to 9.1

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/CaptureParameterNameTransformation.java
- core/src/main/java/org/kohsuke/stapler/CapturedParameterNames.java
- core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
- core/src/test/java/org/kohsuke/stapler/ClassDescriptorTest.java
See https://github.com/stapler/stapler/pull/225#pullrequestreview-667138790. Unfortunately it does not seem to work consistently—the test passes using my IDE’s compile-on-save mode, but not via `mvn clean test`. If I am following correctly, the `LocalVariableTable` always includes the parameter names, which are then redundantly included in a `MethodParameters` section only when compiled with debug information? Need to look into why this would be. I suspect the difference is between bytecode and runtime retention.
> Remove ASM dep from `ClassDescriptor`

- core/pom.xml
- groovy/pom.xml
- jruby/pom.xml
- pom.xml
Supersedes #241. Yes I hate Mockito too, but we're going to use it we might as well use the latest version.
> Bump Mockito from 1.8.5 to 3.11.0

- .github/dependabot.yml
As in https://github.com/jenkinsci/jenkins/pull/5226 we would like to suppress the likes of #239.
> Ignore new versions of the Servlet API

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
- core/src/main/java/org/kohsuke/stapler/DispatchValidator.java
- core/src/main/java/org/kohsuke/stapler/EvaluationTrace.java
- core/src/main/java/org/kohsuke/stapler/Facet.java
- core/src/main/java/org/kohsuke/stapler/HttpRedirect.java
- core/src/main/java/org/kohsuke/stapler/HttpResponses.java
- core/src/main/java/org/kohsuke/stapler/LocaleDrivenResourceProvider.java
- core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
- core/src/main/java/org/kohsuke/stapler/ScriptExecutor.java
- core/src/main/java/org/kohsuke/stapler/ScriptRequestDispatcher.java
- core/src/main/java/org/kohsuke/stapler/StaplerResponse.java
- core/src/main/java/org/kohsuke/stapler/StaplerResponseWrapper.java
- core/src/main/java/org/kohsuke/stapler/export/ClassAttributeBehaviour.java
- core/src/main/java/org/kohsuke/stapler/export/DataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/JSONDataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/main/java/org/kohsuke/stapler/export/ModelBuilder.java
- core/src/main/java/org/kohsuke/stapler/export/Property.java
- core/src/main/java/org/kohsuke/stapler/export/XMLDataWriter.java
- core/src/main/java/org/kohsuke/stapler/interceptor/RequirePOST.java
- core/src/main/java/org/kohsuke/stapler/json/JsonHttpResponse.java
- core/src/main/java/org/kohsuke/stapler/lang/Klass.java
- core/src/main/java/org/kohsuke/stapler/lang/KlassNavigator.java
- core/src/main/java/org/kohsuke/stapler/lang/MethodRef.java
- core/src/test/java/org/kohsuke/stapler/ClassDescriptorTest.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/DefaultScriptInvoker.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyFacet.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/ScriptInvoker.java
- jruby/src/main/java/org/kohsuke/stapler/jelly/jruby/RubyMethodRef.java
https://github.com/stapler/stapler/pull/235#pullrequestreview-673514424
> Switch to `spotbugs-annotations`

- jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/AdjunctManager.java
When you request http://localhost:8080/adjuncts/xxxx/lib/form/link/link.js it's working as expected but when you try with just /adjuncts/xxxx (without rest of path), the [path](https://github.com/stapler/stapler/blob/b7831000ac197901b65716a4d48eac2f0b100eb3/jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/AdjunctManager.java#L159) is an empty String and thus, cannot call `charAt(0)` on it, leading to a 500 error.
> Prevent 500 response when adjunct is empty

- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
- jelly/pom.xml
- jruby/pom.xml
- pom.xml
- src/spotbugs/spotbugs-excludes.xml
Like #289 but with SpotBugs warnings suppressed and some Enforcer changes.
> Bump parent POM from 1.65 to 1.69

- core/src/test/java/org/kohsuke/stapler/interceptor/JsonOutputFilterTest.java
Newer versions of Jetty delete this class, so we might as well stop relying on it. We already depend on `net.sf.json` elsewhere, so might as well use that instead.
> Replace deprecated `org.eclipse.jetty.util.ajax.JSON` with non-deprecated `net.sf.json`

- core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/SourceGeneratingAnnotationProcessor.java
Some tests were still using Java 6. This updates them to use Java 8. The addition of `-Xlint:none` is because otherwise the tests fail with erors like "warning: Supported source version `RELEASE_6` from annotation processor `net.java.dev.hickory.prism.internal.PrismGenerator` less than `-source 1.8`". Fixing this would require patching `PrismGenerator`, which doesn't even exist on GItHub (much less with any activity in the past decade), or finding some other library or method of testing annotation processors, both of which are a bit more effort than I'm willing to put in at the moment, so silencing the linter warnings in the tests seemed like the easiest choice.
> Use Java 8 in annotation tests

- core/src/main/java/org/kohsuke/stapler/AcceptHeader.java
- core/src/main/java/org/kohsuke/stapler/Ancestor.java
- core/src/main/java/org/kohsuke/stapler/DataBoundSetter.java
- core/src/main/java/org/kohsuke/stapler/HttpResponse.java
- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/StaplerRequest.java
- core/src/main/java/org/kohsuke/stapler/StaplerResponse.java
- core/src/main/java/org/kohsuke/stapler/WebMethod.java
- core/src/main/java/org/kohsuke/stapler/config/ConfigurationLoader.java
- core/src/main/java/org/kohsuke/stapler/export/CustomExportedBean.java
- core/src/main/java/org/kohsuke/stapler/export/PythonDataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/RubyDataWriter.java
- core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
- core/src/main/java/org/kohsuke/stapler/framework/errors/NoHomeDirError.java
- core/src/main/java/org/kohsuke/stapler/framework/io/LineEndNormalizingWriter.java
- core/src/main/java/org/kohsuke/stapler/json/JsonBody.java
- core/src/main/java/org/kohsuke/stapler/json/SubmittedForm.java
- jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/AdjunctManager.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyClassTearOff.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java
- jsp/src/main/java/org/kohsuke/stapler/tags/Include.java
Without this, building with Java 11 fails with "error: tag not supported in the generated HTML version: tt" for whatever reason.
> Use `@code` rather than `<tt>`

- core/pom.xml
- groovy/pom.xml
- jelly/pom.xml
- jrebel/pom.xml
- jsp/pom.xml
- pom.xml
Adopts the [POM Code Convention](https://maven.apache.org/developers/conventions/code.html#pom-code-convention) that was [voted on by Maven developers in 2008](https://lists.apache.org/thread/h8px5t6f3q59cnkzpj1t02wsoynr3ygk). Note that this PR adds no automation; this is just a one-time pass.
> Adopt POM Code Convention

- core/pom.xml
- jelly/pom.xml
- pom.xml
Now that JRuby support has been dropped, some entries in the main `pom.xml` file's `dependencyManagement` section (which were originally there to apply to multiple modules) are now unneeded and can be moved into the corresponding module. This improves readability by keeping the dependency definition closer to where it is actually used.
> Dependency cleanup

- core/pom.xml
Version 1.3.5 is the last version prior to the Jakarta package renaming. Thus it is compatible with our existing consumers.
> Bump `annotation-api` from 1.3.2 to 1.3.5

- core/src/main/java/org/kohsuke/stapler/framework/io/WriterOutputStream.java
Noticed while testing the incremental build of #320, which was built with Java 11. The Java 11 Jenkins test run passed, but the Java 8 Jenkins test run failed with `ByteBuffer`-related `NoSuchMethodError` issues. I could reproduce locally. Looking into this further, it appears that Java 11 implemented used covariance in the return type of some `ByteBuffer` methods, which breaks when running on Java 8. Downcasting to the base class works around the problem.
> Fix `ByteBuffer`-related `NoSuchMethodError` issues

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/DataBoundSetter.java
- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/framework/io/WriterOutputStream.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
Core ships the Java EE annotation API, which is consumed both in core itself and in Stapler (a core dependency). Specifically, we consume `javax.annotation.PostConstruct`. `configuration-as-code`, `coverity`, `datetime-constraint`, `opentelemetry`, and `strict-crumb-issuer` consume `javax.annotation.PostConstruct` from core. `coverity`, `jira`, and `opentelemetry` consume `javax.annotation.PreDestroy` from core. `gitlab-plugin` consumes `javax.annotation.Priority` from core. All of these are subject to Jakarta package renames. This means we need to come up with a migration plan.
This PR begins a migration by shipping both the old `javax.annotation` classes and the new `jakarta.annotation` classes, adjusting Stapler to check both `jakarta.annotation.PostConstruct` and …
> Begin migration to Jakarta Annotations

- core/src/main/java/org/kohsuke/stapler/Function.java
- core/src/main/java/org/kohsuke/stapler/StaticViewFacet.java
- core/src/main/java/org/kohsuke/stapler/lang/FieldRef.java
The fewer third-party dependencies we have, the easier maintenance becomes. This PR removes usages of the third-party `StringUtils#join` method in favor of native Java Platform functionality.
> Remove usages of `StringUtils#join`

- core/src/main/java/org/kohsuke/stapler/HttpResponses.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/IncludeTag.java
- src/spotbugs/spotbugs-excludes.xml
Removes no-longer-necessary suppressions, and moves the still-necessary suppressions from `src/spotbugs/spotbugs-excludes.xml` to `@SuppressFBWarnings` annotations in the relevant code (where they are more likely to be noticed and fixed) if there were a reasonable number of them.
> Clean up SpotBugs exclusions

- docs/getting-started.adoc
- docs/reference.adoc
When browsing the documentation on GitHub, the links are broken as they
refer to an HTML document, which has been changed to adoc in commit
ff4f5b4916fbfc8017d1b38298b103a19ed0a987.
> Fix docs references to html files (use .adoc)

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
**Untested** PR to return better error messages for users who are affected by tables-to-divs issues. In [JENKINS-67218](https://issues.jenkins.io/browse/JENKINS-67218) and [JENKINS-67550](https://issues.jenkins.io/browse/JENKINS-67550), a tables-to-divs issue caused the frontend to send a list of classes rather than a single class to the backend. This list eventually made its way to the class loader, resulting in confusing error messages. Users thought that the classloader couldn't load the classes because they weren't present, but the real reason class loading is failing is that we're passing a list rather than a single class to the class loader. This PR changes the code to fail fast in this situation and give the user an informative error message before the problem makes its way to …
> Fail fast when the frontend sends an invalid class name

- groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
https://github.com/jenkinsci/stapler/pull/343#pullrequestreview-916172436
> Test coverage for `StaplerClosureScript._`

- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovierJellyScript.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/StaplerClosureScript.java
Compiling Stapler with Java 11 and `<release>11</release>` yields the following results:
```
[ERROR] jenkinsci/stapler/groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/StaplerClosureScript.java:[30,18] error: as of release 9, '_' is a keyword, and may not be used as an identifier
[ERROR] jenkinsci/stapler/groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/StaplerClosureScript.java:[31,15] error: as of release 9, '_' is a keyword, and may not be used as an identifier
[ERROR] jenkinsci/stapler/groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/StaplerClosureScript.java:[38,18] error: as of release 9, '_' is a keyword, and may not be used as an identifier
```
Rename the two _ functions as `gettext`, which is a valid Java 9+ identifier.
For backward compatibility with scripts like …
> [JENKINS-67911] Stapler does not compile with Java 11

- core/pom.xml
- groovy/pom.xml
- groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
- jelly/pom.xml
- jelly/src/test/java/org/kohsuke/stapler/jelly/AttributeExpressionTest.java
- jelly/src/test/java/org/kohsuke/stapler/jelly/BodyExpressionTest.java
- jelly/src/test/resources/org/kohsuke/stapler/jelly/AttributeExpressionTest/index.jelly
- jelly/src/test/resources/org/kohsuke/stapler/jelly/BodyExpressionTest/index.jelly
- pom.xml
See [JENKINS-68215](https://issues.jenkins.io/browse/JENKINS-68215). Thanks to @NotMyFault for identifying this Java 17 issue in Stapler. This PR does not resolve the issue, but it adds two tests demonstrating the issue in Jelly views (which pass on Java 8 and Java 11 but fail on Java 17) as well as a test demonstrating that the issue is not present in Groovy views (which passes on Java 8, Java 11, and Java 17).
> Add tests for JENKINS-68215

- core/src/main/java/org/kohsuke/stapler/AnnotationHandler.java
- core/src/main/java/org/kohsuke/stapler/ClassLoaderValue.java
- core/src/main/java/org/kohsuke/stapler/MetaClassLoader.java
- core/src/main/java/org/kohsuke/stapler/TearOffSupport.java
- core/src/main/java/org/kohsuke/stapler/WebApp.java
- core/src/main/java/org/kohsuke/stapler/export/ModelBuilder.java
- core/src/main/java/org/kohsuke/stapler/lang/Klass.java
- core/src/main/java/org/kohsuke/stapler/lang/KlassNavigator.java
- core/src/test/java/org/kohsuke/stapler/MetaClassLoaderTest.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
- groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
- jrebel/src/main/java/org/kohsuke/stapler/JRebelFacet.java
Generally a good idea for avoiding memory leaks, though that may not be a real issue in Jenkins since the `ClassLoader`s involved are those of plugins, which would never be collected during the JVM session anyway.
Motivated by a CloudBees CI thread dump showing a large number of threads blocked like this:
```
"Handling HEAD /jenkins/instance-identity/ from … : Jetty (winstone)-…" …
- waiting to lock <…> (a java.util.HashMap)
owned by "Handling GET /jenkins/job/someItem/configure from … : Jetty (winstone)-… SomeStuff/configure.jelly" …
at org.kohsuke.stapler.WebApp.getMetaClass(WebApp.java:227)
at org.kohsuke.stapler.WebApp.getMetaClass(WebApp.java:244)
at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)
at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
at …
```
> Use `ClassValue` for caching

- core/src/main/java/org/kohsuke/stapler/CaptureParameterNameTransformation.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/TokenList.java
- core/src/main/java/org/kohsuke/stapler/bind/Bound.java
- core/src/main/java/org/kohsuke/stapler/export/Model.java
- core/src/main/java/org/kohsuke/stapler/jsr269/ConstructorProcessor.java
- core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
- core/src/test/java/org/kohsuke/stapler/export/ModelTest.java
- core/src/test/java/org/kohsuke/stapler/export/XMLDataWriterTest.java
- core/src/test/java/org/kohsuke/stapler/lang/KlassTest.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/GroovyFacet.java
- groovy/src/test/java/org/kohsuke/stapler/jelly/groovy/GroovyClassLoaderTearOffTest.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/AnnotationProcessorImpl.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/InternationalizedStringExpression.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyFacet.java
Testing done: [Core test suite passed](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6700/13/), [BOM test suite passed](https://ci.jenkins.io/job/Tools/job/bom/job/PR-1234/5/)
> Use Java 11 language features where possible

- jelly/src/test/java/org/kohsuke/stapler/jelly/ResourceBundleTest.java
This assumption is no longer necessary now that we are on a Java 11 baseline.
> Remove unnecessary assumption

- core/src/main/java/org/kohsuke/stapler/WebApp.java
Indulging in some premature optimization by avoiding the need to enter the `synchronized` block in the common case where `WebApp#classMap` is already initialized. Implements the safe idiom described [here](https://errorprone.info/bugpattern/DoubleCheckedLocking).
> Double-checked locking for `WebApp#classMap`

- core/pom.xml
- core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/SourceGeneratingAnnotationProcessor.java
- core/src/test/java/org/kohsuke/stapler/jsr269/Utils.java
- pom.xml
We currently test our annotation processors with [Hickory](https://github.com/vietj/hickory), an outdated library that hasn't been maintained in over a decade. This PR switches us to [Elementary](https://github.com/Pante/elementary), a modern and well-maintained annotation processor testing library. Note that Elementary requires both Java 11 and JUnit 5, both of which we now support.
> Migrate from Hickory to Elementary

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/BytecodeReadingParanamer.java
- core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
- core/src/test/java/org/kohsuke/stapler/ClassDescriptorTest.java
One of my goals for reducing core dependency debt is to remove ASM from core (possibly by detaching it into a library plugin), which means first removing any usages of ASM from core. A big one was JNR, which I have already detached. Stapler is probably the second-biggest one.
This PR replaces the ASM dependency with an inlined copy of https://github.com/paul-hammant/paranamer/blob/master/paranamer/src/java/com/thoughtworks/paranamer/BytecodeReadingParanamer.java which is basically just the portions of ASM that we need, inlined into a single file. This removes the risk of linkage errors because we're just invoking a regular static method on a regular Java class, and it brings us one step forward to removing ASM from the core WAR.
One might be concerned about the fact that we're unlikely to …
> Remove ASM dependency

- jelly/pom.xml
- pom.xml
Upgrades these two in-house Maven plugins to the latest releases I just put out today (with Maven 3 APIs).
> Upgrade Maven Jellydoc and Stapler plugins

- core/src/main/java/org/kohsuke/stapler/ClassLoaderValue.java
Amending #370. https://github.com/jenkinsci/email-ext-plugin/pull/311 etc. were filed because it turned out there were problems running `plugin-compat-tester` against plugins still using PowerMock (discouraged: https://github.com/jenkinsci/plugin-pom/pull/442):
```
java.lang.ExceptionInInitializerError
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:315)
at javassist.runtime.Desc.getClassObject(Desc.java:72)
at javassist.runtime.Desc.getClassType(Desc.java:181)
at javassist.runtime.Desc.getType(Desc.java:151)
at javassist.runtime.Desc.getType(Desc.java:107)
at io.jenkins.blueocean.service.embedded.BaseTest.<init>(BaseTest.java:46)
at io.jenkins.blueocean.service.embedded.ContainerFilterTest.<init>(ContainerFilterTest.java:34)
at … …
```
> Make `ClassLoaderValue` compatible with PowerMock

- core/src/main/java/org/kohsuke/stapler/Stapler.java
Existing logic introduced in https://github.com/jenkinsci/stapler/commit/1a07292090c93748eccdf1864a4e327941db8fc6
> Some exception handling that was forgotten as part of JEP-227

- core/pom.xml
- core/src/test/java/org/kohsuke/stapler/compression/CompressionFilterTest.java
This library has been deprecated for well over a decade and was recently removed from core.
> Remove usages of Commons HttpClient 3.x from tests

- Jenkinsfile
Follow-up of https://github.com/jenkins-infra/jenkins-infra/pull/2630, restore Artifact Caching Proxy disabled in [`0da3f90` (#439)](https://github.com/jenkinsci/stapler/pull/439/commits/0da3f9010cbb570d3811808482ed9adfbeeb0d8c).
The ACP now ignores `elementary-releases` Maven repository as the `com.karuslabs:elementary:jar:1.1.3` artifact isn't published on Maven Central.
Closes #440 
Closes https://github.com/jenkins-infra/helpdesk/issues/3382
> Restore Artifact Caching Proxy

- docs/jelly-taglib-ref.adoc
- docs/taglib-jelly.xsd
The tag does already exist, see https://github.com/jenkinsci/stapler/blob/cea4497990e88143e543410ea0817c15b3e86d1a/jelly/src/main/java/org/kohsuke/stapler/jelly/AttributeTag.java#L75-L79, yet remained undocumented.
This PR takes care of that.
> Document 'since' attribute tag

- core/src/main/resources/org/kohsuke/stapler/bind.js
The object passed to the callback was only ever documented to have a `responseObject` method that, when invoked, returned JSON, but in practice various consumers had come to depend on this returning a Prototype [Ajax.Response](http://api.prototypejs.org/ajax/Ajax/Response/index.html) object. Already when developing #452 I observed the need for a `responseText` field to satisfy consumers in Jenkins core, but I did not think that anybody consuming the JSON representation would be using the undocumented `responseJSON` field instead of the documented `responseObject()` function to retrieve this data. Well, the ECharts API plugin does. This is arguably an abuse of this API, but at this point it is too late to correct all consumers: we might as well accept that this is part of the expected …
> [JENKINS-71236] Stapler Ajax Proxy is broken (regression in 2.404)

- pom.xml
This fixes a very small annoyance while building the project: both the aggregator and the `core` module have the same name, so the maven summary ended up like
```
[INFO] Reactor Summary for Stapler Parent 999999-SNAPSHOT:
[INFO]
[INFO] Stapler ............................................ SUCCESS [  0.367 s]
[INFO] Stapler ............................................ SUCCESS [  0.178 s]
[INFO] Stapler JSP module ................................. SUCCESS [  0.031 s]
[INFO] Stapler Jelly module ............................... SUCCESS [  0.041 s]
[INFO] Stapler Groovy module .............................. SUCCESS [  0.067 s]
[INFO] Stapler JRebel module .............................. SUCCESS [  0.030 s]
[INFO] ------------------------------------------------------------------------
```
which …
> Adjust Stapler parent module name and description

- core/src/main/java/org/kohsuke/stapler/bind/BoundObjectTable.java
[JENKINS-72113](https://issues.jenkins.io/browse/JENKINS-72113)
```[tasklist]
```
> [JENKINS-72113] Relax serialization of `BoundObjectTable.Table`

- pom.xml
Reverts jenkinsci/stapler#500
https://github.com/HtmlUnit/htmlunit/issues/669
> Revert "Bump org.jenkins-ci.main:jenkins-test-harness-htmlunit from 161.v786c2c610d65 to 162.va_4918b_f36d72"

- core/src/main/java/org/kohsuke/stapler/AbstractTearOff.java
Was curious about speed of loading Groovy views during first startup.
> Log in `AbstractTearOff` about time to parse resources

- core/src/main/java/org/kohsuke/stapler/jsr269/AbstractProcessorImpl.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
This is somewhat hacky, but it is effective, and I believe it is the best we can do on Java 11/17.
Fixes #526
The included test fails before this PR and passes after.
> `.stapler` file generation is nondeterministic

- core/src/main/java/org/kohsuke/stapler/BytecodeReadingParanamer.java
The use of `BytecodeReadingParanamer` is not sustainable in the long term, so introduce a warning to more aggressively call out plugins that are still being built with an ancient HPI/JPI toolchain. I tried this out on the plugins in BOM and none of them showed a warning. Print the warning only a single time per signature to avoid spamming log files.
The only plugin I am aware of that will trigger this warning in production is the Gradle plugin.
Compiled Text Finder with `mvn clean verify -Dmaven.compiler.parameters=false` and saw these warning as expected:
> `o.k.s.BytecodeReadingParanamer#lookupParameterNames`: Looking up parameter names for `public hudson.util.FormValidation hudson.plugins.textfinder.TextFinder$DescriptorImpl.doCheckRegexp(java.lang.String)`; update plugin to a version …
> Log warning when doing bytecode analysis

- pom.xml
More concise to use a BOM than manage individual package versions.
> Use `jetty-bom`

- core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
After #539, we're consistently referring to servlet response codes with the syntax `HttpServletResponse.SC*` except here. Make it consistent.
> Consistently prefix servlet response codes with class name

- core/pom.xml
- core/src/main/java/org/apache/commons/fileupload/FileItem.java
- core/src/main/java/org/apache/commons/fileupload/FileItemHeaders.java
- core/src/main/java/org/apache/commons/fileupload/InvalidFileNameException.java
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/StaplerRequest.java
- core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
See https://github.com/jenkinsci/jenkins/pull/9259 for the PR description.
See https://github.com/jenkinsci/jenkins/pull/9259.
> [JENKINS-73170] Upgrade Commons FileUpload from 1.5 to 2.0.0-M2

- core/pom.xml
- core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/compression/CompressionServletResponse.java
- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
See jenkinsci/workflow-api-plugin#134, jenkinsci/cloudbees-folder-plugin#174, and jenkinsci/docker-build-step-plugin#75. [JZlib](https://github.com/ymnk/jzlib) has not been updated since 2013. Since then, [`GZIPInputStream`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPInputStream.html) and [`GZIPOutputStream`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPOutputStream.html) have been added to the Java 7 API, so it seems more prudent to use those implementations.
To verify the correctness of the change to `Stapler#isSocketException(Throwable)`, compare the upstream error messages from [JZlib](https://github.com/ymnk/jzlib/blob/a21be20213d66eff15904d925e9b721956a01ef7/src/main/java/com/jcraft/jzlib/DeflaterOutputStream.java#L90) and …
> Use Java 7 versions of `GZIPInputStream` and `GZIPOutputStream`

- core/src/main/java/org/kohsuke/stapler/compression/FilterServletOutputStream.java
After upgrading to latest bits, I started seeing the following log spam when running Jenkins locally:
```
java.lang.NullPointerException: Deflater has been closed
at java.base/java.util.zip.Deflater.ensureOpen(Deflater.java:902)
at java.base/java.util.zip.Deflater.deflate(Deflater.java:564)
at java.base/java.util.zip.Deflater.deflate(Deflater.java:464)
at java.base/java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:163)
at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:244)
at org.kohsuke.stapler.compression.FilterServletOutputStream.close(FilterServletOutputStream.java:45)
at org.kohsuke.stapler.compression.CompressionServletResponse.close(CompressionServletResponse.java:73)
at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFil …
```
> `NullPointerException`: "Deflater has been closed" emanating from `FilterServletOutputStream`

- core/src/main/java/org/kohsuke/stapler/AncestorImpl.java
- core/src/main/java/org/kohsuke/stapler/BytecodeReadingParanamer.java
- core/src/main/java/org/kohsuke/stapler/ClassDescriptor.java
- core/src/main/java/org/kohsuke/stapler/Header.java
- core/src/main/java/org/kohsuke/stapler/MetaClass.java
- core/src/main/java/org/kohsuke/stapler/QueryParameter.java
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/TokenList.java
- core/src/main/java/org/kohsuke/stapler/export/XMLDataWriter.java
- core/src/main/java/org/kohsuke/stapler/jsr269/ConstructorProcessor.java
- core/src/main/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessor.java
- core/src/test/java/org/kohsuke/stapler/StaplerTest.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
- jelly/src/main/java/org/kohsuke/stapler/framework/adjunct/AdjunctManager.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/InternationalizedStringExpression.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/ResourceBundle.java
Like https://github.com/jenkinsci/jenkins/pull/9383, but for this repository.
> Use `isEmpty()` where possible

- core/src/main/java/org/kohsuke/stapler/HttpResponseRenderer.java
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/WebApp.java
- core/src/main/java/org/kohsuke/stapler/bind/BoundObjectTable.java
- core/src/main/java/org/kohsuke/stapler/export/TypeUtil.java
- groovy/src/main/java/org/kohsuke/stapler/jelly/groovy/JellyBuilder.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/CustomJellyContext.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/DefaultScriptInvoker.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/IncludeTag.java
- jelly/src/main/java/org/kohsuke/stapler/jelly/JellyClassTearOff.java
Like https://github.com/jenkinsci/jenkins/pull/9382, but for this repository.
> Use pattern matching for `instanceof`

- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/main/java/org/kohsuke/stapler/WebApp.java
In practice this map is always empty, since I checked Jenkins and CloudBees sources and nothing ever writes to the map. The only reader besides Stapler is https://github.com/jenkinsci/scm-api-plugin/blob/a24e62fa67977d1c381b922a1a745afb725771c7/src/main/java/jenkins/scm/api/SCMFile.java#L422. Altogether I can't see a good reason to retain this feature; the servlet container should always be the source of truth and this seems like yet another case of Stapler over-reaching in scope. Simpler to deprecate this feature and remove it eventually.
> Deprecate `WebApp#mimeTypes`

- core/src/main/java/org/kohsuke/stapler/HttpResponses.java
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
See https://github.com/jenkinsci/workflow-cps-plugin/pull/907#discussion_r1691371292.
> Define `HttpResponses.wrap` and use from `RequestImpl.invokeConstructor`

- core/src/main/java/org/kohsuke/stapler/jsr269/AbstractProcessorImpl.java
- core/src/main/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessor.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ConstructorProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/ExportedBeanAnnotationProcessorTest.java
- core/src/test/java/org/kohsuke/stapler/jsr269/QueryParameterAnnotationProcessorTest.java
While recently attempting to debug an annotation processor, I found that all notices were being discarded, apparently due to an [IntelliJ issue](http://youtrack.jetbrains.net/issue/IDEA-71822) from 13 years ago that appears to have been resolved since then. This PR re-enables logging of notices and adapts the tests to expect them.
> Improve debugging support for annotation processors

- core/src/main/resources/org/kohsuke/stapler/bind.js
Now that Prototype.js has been removed from core, this code can be simplified.
> Remove legacy Prototype.js code

- core/src/main/java/org/kohsuke/stapler/Stapler.java
- core/src/test/java/org/kohsuke/stapler/StaplerTest.java
https://github.com/jenkinsci/jenkins/blob/e1a6b190d4d71e95a8e00facd52ce7718909b9e8/core/src/main/java/hudson/model/TopLevelItemDescriptor.java#L146-L175 seems to assume this method can be called safely and return null. (I tried to write an integration test but every `TopLevelItemDescriptor` subclass seems to override this method.) https://github.com/jenkinsci/support-core-plugin/blob/a85622b87b52a0ebaf3ecf97c7a443df546e4242/src/main/java/com/cloudbees/jenkins/support/impl/AboutJenkins.java#L507-L517 notes the poor behavior.
> Undocumented NPE if `Stapler.getCurrent()` called outside an HTTP handling thread

- core/maven-example/pom.xml
- core/maven-example/src/main/java/example/BookStore.java
* Migrate from StaplerRequest and StaplerResponse to "StaplerRequest2" and "StaplerResponse2" as the earlier are deprceated now.
* Update the pom.xml dependencies preventing conflicts with new migrations and making pom.xml up to date.
* here is a screenshot testing "/hello" after migration
> Migrate example to StaplerRequest2 & StaplerResponse2

- core/maven-example/pom.xml
- core/maven-example/src/main/java/example/Book.java
Since Stapler is using Jakarta EE 9, Change the version of Jakarta to be 5.0.0 (EE 9)
> Modify dependency from EE 10 to EE 9 && Migrate maven-example/Book.java to StaplerRequest2 & StaplerResponse2

- core/src/main/java/org/kohsuke/stapler/ResponseImpl.java
[JENKINS-75224](https://issues.jenkins.io/browse/JENKINS-75224)
`mvn clean install -Dtest='ApiTest,UpdateCenterTest,DefaultCrumbIssuerTest'` in core
Compared https://ci.jenkins.io/contextMenu?jsonp=callback (`?jsonp` supported) to http://localhost:8080/jenkins/contextMenu?jsonp=callback (`?jsonp` ignored, looks like JSON now).
> [JENKINS-75224] Remove support for `?jsonp` parameter in JSON flavor

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
- core/src/test/java/org/kohsuke/stapler/DataBindingTest.java
- core/src/test/java/org/kohsuke/stapler/MockRequest.java
- core/src/test/java/org/kohsuke/stapler/RequestImplTest.java
Noticed in CloudBees CI a stack trace under certain conditions (Move/Copy/Promote) now reproduced in a test
```
java.lang.UnsupportedOperationException
at java.base/java.util.Collections$UnmodifiableMap.putAll(Collections.java:1665)
at org.kohsuke.stapler.RequestImpl.getParameterMap(RequestImpl.java:266)
at org.kohsuke.stapler.RequestImplTest.test_multipart_formdata(RequestImplTest.java:177)
```
First of all, `getParameterMap` is documented to return an immutable map. This was true in `javax.servlet` days, so not obviously a `jakarta.servlet` regression, though of course a particular version of Jetty might have started to enforce immutability.
Secondly, the return type was wrong! The value type is supposed to be `String[]`, not `String`. We were using rawtypes and so did not notice.
Both …
> [JENKINS-70756] Incorrect `RequestImpl.getParameterMap`

- core/src/main/java/org/apache/commons/fileupload/FileItem.java
- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
Fixes the root cause behind https://github.com/jenkinsci/file-parameters-plugin/issues/199. While https://github.com/jenkinsci/file-parameters-plugin/pull/215 chased away this problem by migrating away from the compatibility layer, the compatibility layer might still be in use in other plugins.
CI build
> Fix NPE in `FileItem` compatibility layer

- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
https://github.com/jenkinsci/jenkins/pull/10236#issuecomment-2784870058 alternative.
Requires https://github.com/jenkinsci/jenkins/pull/10515.
Testing notes in https://github.com/jenkinsci/workflow-job-plugin/pull/528.
> More efficient `LargeText.doProgressText`

- core/src/main/java/org/kohsuke/stapler/bind/Bound.java
- pom.xml
Someone reported to us that the URL portion was not properly escaped in URLs like the following, resulting in broken JS:
`http://localhost:8080/$stapler/bound/script/foo'bar'baz?var=proxy&methods=foo,bar`
Previously output was:
`proxy = makeStaplerProxy('/foo'bar'baz','a534b6b86f174fb6a2180a8cc9ad94589eabfc75149c2e1faec6fc2a5448a275',['bar','foo']);`
Now output is:
`proxy = makeStaplerProxy('/foo\'bar\'baz','a534b6b86f174fb6a2180a8cc9ad94589eabfc75149c2e1faec6fc2a5448a275',['bar','foo']);`
This is in the code branch for `WithWellKnownURL` which hasn't had an implementation in about a decade as far as I'm aware, and even before it wasn't in a relevant plugin. This fixes the case for when there's ever a `WithWellKnownURL` that has single quotes in its URL.
There is no security impact, so …
> Escape values inside JS string

- core/src/main/java/org/kohsuke/stapler/RequestImpl.java
Instead of just ignoring them and logging a warning, these should be bubbled up the same way as `@DataBoundConstructor` constructors.
Implement a `setXXX` method annotated with @DataBoundSetter, throwing a `Descriptor.FormException`. Verified that the corresponding message gets displayed when saving using "Save" and "Apply" from a Jenkins form, instead of an incorrect configuration being applied silently.
> Bubble up exceptions from calling `@DataBoundSetter` methods

- core/src/main/java/org/kohsuke/stapler/framework/io/LargeText.java
- core/src/test/java/org/kohsuke/stapler/framework/io/LargeTextTest.java
- Part of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/704
As suggested in https://github.com/jenkinsci/stapler/pull/703#pullrequestreview-3107730846 and based on the guidance in https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/704 to avoid hacks in favor of upgrading the minimum Jenkins version for plugins, this PR is adding an interface based constructor for `LargeText`.
It will be used by the `workflow-api` plugin for a streaming based step log implementation.
(https://github.com/das7pad/jenkins-workflow-api-plugin/commit/71f6322ee1e754e4777f33b0a050fbf0aee6e785#diff-fa50e2c142db03c7b1d36cd1c8bf3be413f1e375ef7d0f28ca0e1889c49238d8R384-R392 -- With this PR merged and stapler upgraded in a Jenkins weekly, we can pull it into the plugin and avoid the hack.) …
> Add interface based constructor for LargeText
